### ISSUE TITLE
大神请教个问题

### ISSUE THREAD

**Issue by LeeGG** [clockknock/wallet#1]
如果我想做基于以太的多币种的钱包。怎么搞？

**Comment by LeeGG** [comment]
在你这个钱包基础上。能给个思路吗

**Comment by clockknock** [comment]
https://medium.com/@piyopiyo/how-to-send-erc20-token-with-web3-js-1-0-0-95164b32e9a6 <https://medium.com/@piyopiyo/how-to-send-erc20-token-with-web3-js-1-0-0-95164b32e9a6> 我还没搞过,不过你可以看看这个,web3js 1.0.0的ERC20交互.

**Comment by LeeGG** [comment]
多谢🙏
